# Fly.io Configuration
# https://fly.io/docs/reference/configuration/

app = "wild-kratts-mcp-server"
primary_region = "sea"
console_command = "/app/bin/bash"

[build]
dockerfile = "Dockerfile"

[env]
PYTHON_VERSION = "3.12.4"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "5s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

# Auto-scaling configuration
[scaling]
min_count = 0
max_count = 10

# Optional: Multiple regions
# [[regions]]
# name = "sea"  # Seattle
# 
# [[regions]]  
# name = "lhr"  # London