# Railway Configuration
# https://docs.railway.app/reference/config-file

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
numReplicas = 1
sleepThreshold = "30m"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python server.py"

[env]
PYTHON_VERSION = "3.12.4"
PYTHONUNBUFFERED = "1"

# Health check configuration
[healthcheck]
httpPath = "/health"
httpTimeout = "10s"